language: node_js

node_js:
  - node
  - 6
  
services:
  - postgresql

before_script:
  - psql -c 'create database dms_test;' -U postgres
  - npm run db:migrate:test

after_script:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info
